"""``live`` profile adapters: the real regulatory corpus, generated by the Gemini API.

The live profile is the demo-facing stack: retrieval serves only the REAL regulator
instruments ingested by ``pipelines.refresh_job``, never the fictional built-in seed.
Everything else reuses the SDK-free local adapters, so custody of the index and the audit
trail stays on the machine.

There is deliberately no local model server. The corpus is fetched from the regulators'
own published sources, so this profile cannot be kept current without leaving the data
centre, and a laptop generator beside that would describe a deployment nobody would buy
(org decision, 2026-08-30). The profile therefore needs Application Default Credentials
and a ``GOOGLE_CLOUD_PROJECT``, and the UI provenance banner states that the runtime is
local while the model is Gemini.
"""
